# Site settings
title: 神秘领域
SEOTitle: 逗比的马老师
header-img: img/post-bg-desk.jpg
email: abcdefghijklmnopqrstuvwxyz@abcdefghijklmnopqrstuvw.xyz
description: "神秘领域"
keyword: "逗比的马老师, 异星工厂, 顶悦幻方, aspd199, Factorio"
url: "http://blog.art8620.com"
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/aspd199/description.git" # you code repository

# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "神秘领域"
sidebar-avatar: /img/null.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     null
# zhihu_username:     null
# github_username:    null
# facebook_username:  null
# jianshu_username:   null
# twitter_username:   null




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: null

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: abcdef                            #生成的clientID
  clientSecret: abcdefghijklmnopqrstuvwxyz    #生成的clientSecret
  repo: null.github.io    #仓库名称
  owner: null    #github用户名
  admin: null
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: abcdefghijklmnopqrstuvwxyz

# Google Analytics
ga_track_id: 'UA-98765432-10'            # Format: UA-xxxxxx-xx
ga_domain: null.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: false                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WWW",
        href: "http://www.art8620.com"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
